kind: Service
apiVersion: v1
metadata:
  name: gke-spot-pod-mutating-webhook-service
  namespace: webhook
spec:
  selector:
    app: gke-spot-mutating-webhook
  ports:
    - port: 443
      targetPort: 443
