kind: Deployment
apiVersion: apps/v1
metadata:
  name: gke-spot-mutating-webhook
  namespace: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-spot-mutating-webhook
  template:
    metadata:
      labels:
        app: gke-spot-mutating-webhook
    spec:
      containers:
        - name: gke-spot-mutating-webhook
          image: dorkamotorka/gke-spot-mutate-webhook:0.6
          imagePullPolicy: Always
          ports:
            - containerPort: 443
          volumeMounts:
            - name: cert
              mountPath: /etc/opt
              readOnly: true
      volumes:
        - name: cert
          secret:
            secretName: gke-spot-webhook-tls
